### ISSUE TITLE
 What [wn.synset(subject) for subject in subject_list] is used for?

### ISSUE THREAD

**Issue by puraminy** [phongnt570/ascent#2]
what does the following line do?

```
ascent/src/pipeline/pipeline.py", line 41, in <listcomp>
    [wn.synset(subject) for subject in subject_list]

```

It can generate the following error for some words, which are absent. 

```

Traceback (most recent call last):
  File "main.py", line 73, in <module>
    pipeline.run(subject_list=subject_list, from_module=from_module, to_module=to_module)
  File "/home/pouramini/ascent/src/pipeline/pipeline.py", line 41, in run
    [wn.synset(subject) for subject in subject_list]
  File "/home/pouramini/ascent/src/pipeline/pipeline.py", line 41, in <listcomp>
    [wn.synset(subject) for subject in subject_list]
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/nltk/corpus/reader/wordnet.py", line 1329, in synset
    raise WordNetError(message % (lemma, pos))
nltk.corpus.reader.wordnet.WordNetError: no lemma 'آزمایش' with part of speech 'n'

```

Anyways, I had some general questions and would be grateful if you guide me.
If I want to use this package for another language (in my case Persian) which modules do you think I must change? How can I connect it to BabelNet or another resource instead of English WordNet? Is WordNet a required step? Also what `wn_wp_map.csv` do?

I must study the associated paper more, and I may modify my questions, but if you already have some guides please let me know.

I also managed to use Google Search instead of Bing search. If you are interested, I could give you the code.

**Comment by phongnt570** [comment]
- The line `[wn.synset(subject) for subject in subject_list]` converts raw strings (e.g., "lion.n.01") to corresponding Synset objects (https://www.nltk.org/howto/wordnet.html). The error you posted is caused by an unknown synset.
- The file `wn_wp_map.csv` contains precomputed wordnet-wikipedia pairings. For each subject, we need to know its reference Wikipedia article which will be used to filter out irrelevant search results. Please refer to the **Document filtering** paragraph in page 5 of the paper for more information.
- Adapting to Persian: To be honest, this repository written by me is heavily tuned for English and kind of _researcher's code_ which is not well documented and not easily maintained. If you want to adapt the method to your language, I think it's not worth the effort of modifying my code. Instead, I think it would be easier for you to re-implement the method and fine-tune the components (e.g., open information extraction, facet labeling, using BabelNet instead of WordNet, etc.) so that they work best for your language. You can read the paper and use my code as a reference. If you have any questions during your implementation, I'll be happy to help.

**Comment by puraminy** [comment]
Thank you very much, and thank you for suggesting help...
